import 'package:api_project/api/get_data.dart';
import 'package:api_project/models/get_product.dart';
import 'package:api_project/models/product.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';

class products extends StatefulWidget {
  @override
  State<products> createState() => _productsState();
}

class _productsState extends State<products> {
  List<Autogenerated> products = [];
  List<Images> image = [];
  bool isloading = true;
  void initstate()async{
    super.initState();
    await getAllproducts();
  }

  Future<void> getAllproducts() async {
    products = await get_data(Dio()).getproduct();
    isloading = false;
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('products'),
      ),
      body: isloading
          ? Center(child: CircularProgressIndicator())
          : ListView.builder(
              padding: const EdgeInsets.all(8),
              itemCount: products.length,
              itemBuilder: (BuildContext context, int index) {
                return Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Product(
                    autogenerated: products[index],
                    img: image[index],
                  ),
                );
              },
            ),
    );
  }
}
