import 'package:api_project/models/get_product.dart';
import 'package:dio/dio.dart';

class get_data {
  final Dio dio;
  get_data(this.dio);

  Future<List<Autogenerated>> getproduct() async {
    var response =
        await dio.get('http://anyabdulla-001-site1.htempurl.com/api/product');
    List<dynamic> jsonData = response.data;
    List<Autogenerated> productlist = [];
    List<Images> image = [];
    Autogenerated autogenerated = Autogenerated();
    Images images = Images();
    for (var json in jsonData) {
      autogenerated = Autogenerated.fromJson(json);
      images = Images.fromJson(json);
      image.add(images);
      autogenerated.images = image;
      productlist.add(autogenerated);
    }
    return productlist;
  }
}
