import 'dart:io';
import 'package:api_project/models/get_product.dart';
import 'package:flutter/material.dart';
class Product extends StatelessWidget {
  const Product({super.key, required this.autogenerated, required this.img});
  final Autogenerated autogenerated;
  final Images img;
  @override
  Widget build(BuildContext context) {
    return Container(
                  decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(10),
                      color: Colors.white10),
                  child: Row(
                    children: [
                      Container(
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(10),
                          child: Image.file(File(img.imagePath.toString()),
                            height: 100,
                            width: 150,
                            fit: BoxFit.cover,
                          ),
                        ),
                      ),
                      SizedBox(
                        width: 10,
                      ),
                      Expanded(
                        child: Container(
                          width: 150,
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.stretch,
                            children: [
                              Text(
                                autogenerated.itemName!,
                                style: TextStyle(
                                  fontSize: 20,
                                ),
                              ),
                              Text(
                                autogenerated.description!,
                                style: TextStyle(
                                    //fontSize: 20,
                                    ),
                              ),
                              Text(
                                'price:'+
                                autogenerated.price.toString(),
                                style: TextStyle(
                                  fontSize: 17,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          ElevatedButton(
                            onPressed: () {},
                            child: Text(
                              'Update',
                              style: TextStyle(color: Colors.white),
                            ),
                            style: ElevatedButton.styleFrom(
                              primary: Colors.blue,
                              textStyle: TextStyle(fontSize: 18),
                              padding: EdgeInsets.symmetric(
                                  vertical: 10, horizontal: 20),
                              shadowColor: Colors.black,
                              elevation: 5,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(
                                    10), // تحديد شكل الحواف
                              ),
                            ),
                          ),
                          SizedBox(height: 10),
                          ElevatedButton(
                            onPressed: () {},
                            child: Text(
                              'Delete',
                              style: TextStyle(color: Colors.white),
                            ),
                            style: ElevatedButton.styleFrom(
                              primary: Colors.red,
                              textStyle: TextStyle(fontSize: 18),
                              padding: EdgeInsets.symmetric(
                                  vertical: 10, horizontal: 20),
                              shadowColor: Colors.black,
                              elevation: 5,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(10),
                              ),
                            ),
                          ),
                        ],
                      )
                    ],
                  ),
      );
    }
  }
